# =================================================================
# CONFIGURACIÓN GENERAL DEL SERVIDOR WEB
# =================================================================
server.port=8080
server.servlet.session.timeout=30m
app.url.estadisticas=http://localhost/Compuedu-API-main/src/main/resources/templates/institucion/estadisticas.php
storage.location=uploads

# ==========================================================================
# VINCULACIÓN CON VARIABLES DE ENTORNO DE RENDER (PRODUCCIÓN DEFINITIVO)
# ==========================================================================

# URL de conexión corregida en camelCase compatible con mysql-connector-j
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED&useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración explícita del motor de persistencia
spring.jpa.database=mysql
spring.jpa.open-in-view=false

# Estrategia de sincronización de esquemas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =================================================================
# NUEVA PERSISTENCIA EN LA NUBE (MONGODB ATLAS)
# =================================================================
spring.data.mongodb.uri=mongodb+srv://jeanpierret06:06092006diaz@cluster0.ymxjlft.mongodb.net/compuedu?appName=Cluster0

# Mapeo de la URL de Python (Usa localhost en tu PC, lee la variable en Render)
app.url.python=${APP_URL_PYTHON:http://localhost:5000}
